tailwind.config = {
    darkMode: "class",
    theme: {
    extend: {
        "colors": {
                "secondary-fixed-dim": "#e9c349",
                "surface-container-highest": "#e5e2e1",
                "on-tertiary-container": "#f3fffc",
                "background": "#fcf9f8",
                "tertiary": "#006860",
                "surface-container-low": "#f6f3f2",
                "on-error": "#ffffff",
                "secondary": "#735c00",
                "primary-fixed": "#ffdad8",
                "surface-variant": "#e5e2e1",
                "surface-dim": "#dcd9d9",
                "inverse-surface": "#313030",
                "inverse-on-surface": "#f3f0ef",
                "surface-bright": "#fcf9f8",
                "on-secondary-fixed": "#241a00",
                "on-surface": "#1c1b1b",
                "outline-variant": "#e4bebc",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#92001c",
                "on-primary-fixed": "#410007",
                "on-error-container": "#93000a",
                "tertiary-container": "#008379",
                "error": "#ba1a1a",
                "outline": "#8f6f6e",
                "surface-container-high": "#eae7e7",
                "on-tertiary": "#ffffff",
                "secondary-container": "#fed65b",
                "primary-fixed-dim": "#ffb3b1",
                "surface-container": "#f0eded",
                "secondary-fixed": "#ffe088",
                "inverse-primary": "#ffb3b1",
                "tertiary-fixed-dim": "#6fd8cc",
                "primary-container": "#db313f",
                "on-surface-variant": "#5b403f",
                "on-tertiary-fixed": "#00201d",
                "on-primary-container": "#fffbff",
                "surface": "#fcf9f8",
                "on-secondary-fixed-variant": "#574500",
                "on-secondary": "#ffffff",
                "on-background": "#1c1b1b",
                "primary": "#e63946",
                "on-secondary-container": "#745c00",
                "error-container": "#ffdad6",
                "tertiary-fixed": "#8cf4e8",
                "on-tertiary-fixed-variant": "#00504a",
                "surface-tint": "#e63946",
                "on-primary": "#ffffff"
        },
        "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
        },
        "spacing": {
                "margin-desktop": "64px",
                "gutter": "24px",
                "unit": "8px",
                "margin-mobile": "20px",
                "container-max": "1280px",
                "section-gap": "120px"
        },
        "fontFamily": {
                "body-md": ["Inter"],
                "headline-lg-mobile": ["Geist"],
                "headline-md": ["Geist"],
                "mono-spec": ["Geist"],
                "display-lg": ["Geist"],
                "body-lg": ["Inter"],
                "label-caps": ["Geist"],
                "headline-lg": ["Geist"]
        },
        "fontSize": {
                "body-md": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "0.03em", "fontWeight": "500"}],
                "mono-spec": ["14px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400"}],
                "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
                "label-caps": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.15em", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}]
        }
    }
    }
};
